id: P000248
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །སངས་རྒྱས་ཀྱི་དུས་ཆེན་རྣམས་དང་གུ་རུའི་ཚེས་བཅུ་སོགས་ཀྱི་ངོས་འཛིན་རྒྱུ་མཚན་ཕན་ཡོན་སོགས་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ། མཁས་གྲུབ་ཆེན་པོ་རྩེ་ལེ་སྣ་ཚོགས་རང་གྲོལ།
  layers:
  - book_title
  - author
  - chapter_title
  - quotation
  id: TSD-TSE-14
web_metadata:
  title:
    en: The Reasons for and Benefits of the Anniversary Celebrations of Buddha and
      Guru Rinpoche
    bo: སངས་རྒྱས་ཀྱི་དུས་ཆེན་རྣམས་དང་གུ་རུའི་ཚེས་བཅུ་སོགས་ཀྱི་ངོས་འཛིན་རྒྱུ་མཚན་ཕན་ཡོན་སོགས་བཞུགས་སོ།།
  collection:
    en: Tsele Natsok Rangdrol Series–  Book 14
    bo: རྩེ་ལེ་སྣ་ཚོགས་རང་གྲོལ།–  དེབ། ༡༤
  author:
    en: Tsele Natsok Rangdrol
    bo: རྩེ་ལེ་སྣ་ཚོགས་རང་གྲོལ།
  pusblisher:
    en: Tsadra Foundation Publishing
    bo: ཙཱ་འདྲ་ཐེབས་རྩ་ཚོགས་པ།
  sku: TSD-TSE-14
  category:
    en: Pith Instructions
    bo: མན་ངག
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: TSD-TSE-14.epub
  description:
    en: ''
    bo: ''
